Update Icons to v3
transferwise/styleguide-components pull request #389
Opened 2022-08-02 14:47 UTC by dozortsev

## Context

## Changes

## Considerations

## Original Pull Request (for version bumps)

## Screenshots/GIFs

### Before

### After

## Checklist

- [ ] All changes are covered by tests

2022-08-02 15:07 UTC, richardmccartney requested changes

2022-08-02 15:07 UTC, richardmccartney commented on src/help/tool-tip/tool-tip.demo.html
> +  <question-mark-circle size="24" tw-tool-tip title="Use data-placement to alter position" data-placement="bottom">
Are we missing the `tw-` prefix here?

2022-08-02 15:07 UTC, richardmccartney commented on package.json
> +  "version": "9.2.1",
Can we bump this to be `v10` as the icons are a new visual breaking change

2022-08-02 15:07 UTC, richardmccartney commented on CHANGELOG.md
> +# v9.2.1
Can we add a little more info on this change log, just state this apart of our new visual rebrand and change to `v10` 👍

2022-08-03 14:01 UTC, jonstieglitz approved these changes

2022-08-03 14:13 UTC, merged